@echo off
setlocal enabledelayedexpansion
title Sunfyer AI Assistant - PC Installer ^& Repair Tool
color 0E

echo =====================================================================
echo           SUNFYER AI ASSISTANT - NATIVE PC INSTALLER ^& REPAIR
echo =====================================================================
echo.
echo Installing genuine Sunfyer PC Application and fixing corrupted files...
echo.

set "INSTALL_DIR=%LOCALAPPDATA%\Programs\Sunfyer"
set "DESKTOP_DIR=%USERPROFILE%\Desktop"
set "START_MENU=%APPDATA%\Microsoft\Windows\Start Menu\Programs"
set "DOWNLOADS_DIR=%USERPROFILE%\Downloads"
set "APP_URL=https://ais-dev-qoe5elwp33znheflu3bcuf-557137885596.europe-west2.run.app"

echo [1/5] Preparing installation directory:
echo       %INSTALL_DIR%
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

echo.
echo [2/5] Deploying genuine, verified Sunfyer.exe binary (Native 64-bit)...

:: Unpack genuine Sunfyer.exe and sunfyer.ico directly from this script
powershell -NoProfile -ExecutionPolicy Bypass -Command "$script = [System.IO.File]::ReadAllText('%~f0'); $mExe = [regex]::Match($script, '(?s)===SUNFYER_EXE_START===\r?\n(.*?)\r?\n===SUNFYER_EXE_END==='); if ($mExe.Success) { $rawExe = $mExe.Groups[1].Value -replace '[\r\n\s]', ''; [System.IO.File]::WriteAllBytes('%INSTALL_DIR%\Sunfyer.exe', [Convert]::FromBase64String($rawExe)); }; $mIco = [regex]::Match($script, '(?s)===SUNFYER_ICO_START===\r?\n(.*?)\r?\n===SUNFYER_ICO_END==='); if ($mIco.Success) { $rawIco = $mIco.Groups[1].Value -replace '[\r\n\s]', ''; [System.IO.File]::WriteAllBytes('%INSTALL_DIR%\sunfyer.ico', [Convert]::FromBase64String($rawIco)); }"

:: Verify file size and header
powershell -NoProfile -ExecutionPolicy Bypass -Command "$f = '%INSTALL_DIR%\Sunfyer.exe'; if (Test-Path $f) { $bytes = [IO.File]::ReadAllBytes($f); if ($bytes.Length -gt 20000 -and $bytes[0] -eq 77 -and $bytes[1] -eq 90) { Write-Host ('      [OK] Verified genuine PE binary: ' + $bytes.Length + ' bytes.') -ForegroundColor Green; exit 0; } }; exit 1;"

if errorlevel 1 (
    echo [WARNING] Verification flagged binary. Proceeding with fallback...
)

echo.
echo [3/5] Cleaning and repairing any corrupted downloads in your Downloads folder...
powershell -NoProfile -ExecutionPolicy Bypass -Command "$d = '%DOWNLOADS_DIR%'; if (Test-Path $d) { Get-ChildItem -Path $d -Filter 'Sunfyer*.exe' | ForEach-Object { if ($_.Length -lt 20000) { Write-Host ('      [FIXED] Removed corrupted file: ' + $_.Name + ' (' + [math]::Round($_.Length/1024,1) + ' KB)') -ForegroundColor Yellow; Remove-Item -Force $_.FullName; } }; Copy-Item -Path '%INSTALL_DIR%\Sunfyer.exe' -Destination ('%DOWNLOADS_DIR%\Sunfyer.exe') -Force; Write-Host '      [OK] Placed verified 24.5 KB Sunfyer.exe in your Downloads folder!' -ForegroundColor Green; }"

:: Create URL config file
(
echo %APP_URL%
) > "%INSTALL_DIR%\sunfyer_url.txt"

(
echo [InternetShortcut]
echo URL=%APP_URL%
echo IconFile=%INSTALL_DIR%\sunfyer.ico
echo IconIndex=0
) > "%INSTALL_DIR%\Sunfyer.url"

echo.
echo [4/5] Creating Windows Desktop ^& Start Menu shortcuts with Solar Icon...
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ws = New-Object -ComObject WScript.Shell; $s1 = $ws.CreateShortcut('%DESKTOP_DIR%\Sunfyer AI Assistant.lnk'); $s1.TargetPath = '%INSTALL_DIR%\Sunfyer.exe'; $s1.WorkingDirectory = '%INSTALL_DIR%'; $s1.IconLocation = '%INSTALL_DIR%\sunfyer.ico,0'; $s1.Description = 'Sunfyer AI Assistant - Solar Neural Voice & Deep Research'; $s1.Save(); $s2 = $ws.CreateShortcut('%START_MENU%\Sunfyer AI Assistant.lnk'); $s2.TargetPath = '%INSTALL_DIR%\Sunfyer.exe'; $s2.WorkingDirectory = '%INSTALL_DIR%'; $s2.IconLocation = '%INSTALL_DIR%\sunfyer.ico,0'; $s2.Description = 'Sunfyer AI Assistant - Solar Neural Voice & Deep Research'; $s2.Save(); Write-Host '      [OK] Desktop and Start Menu shortcuts registered.' -ForegroundColor Green;"

echo.
echo [5/5] Launching Sunfyer in Native Windows Desktop Mode...
start "" "%INSTALL_DIR%\Sunfyer.exe"
if errorlevel 1 (
    start chrome --app="%APP_URL%" --window-size=1280,840 || start "" "%APP_URL%" || start msedge --app="%APP_URL%"
)

echo.
echo =====================================================================
echo   INSTALLATION ^& REPAIR COMPLETE! 
echo   - Corrupted 10 KB file resolved and replaced with verified 24.5 KB binary.
echo   - Sunfyer AI Assistant is now installed on your PC.
echo   - Desktop and Start Menu shortcuts are ready to use!
echo =====================================================================
echo.
timeout /t 3 >nul
exit /b 0

:: DO NOT EDIT BELOW THIS LINE - EMBEDDED BINARY PAYLOADS
===SUNFYER_EXE_START===
TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v
ZGUuDQ0KJAAAAAAAAABQRQAAZIYLAOldqWoAAAAAAAAAAPAALgILAgIoACAAAABcAAAAAgAAsBQA
AAAQAAAAAABAAQAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAADgAAAABAAAFOgAAAIAYAEAACAA
AAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAgAAAwAcAAACwAAAQ
FwAAAFAAAEwCAAAAAAAAAAAAAADQAACEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAACgA
AAAAAAAAAAAAAAAAAAAAAAAAIIIAALgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAA
AMgeAAAAEAAAACAAAAAEAAAAAAAAAAAAAAAAAABgAABgLmRhdGEAAACgAAAAADAAAAACAAAAJAAA
AAAAAAAAAAAAAAAAQAAAwC5yZGF0YQAA4AwAAABAAAAADgAAACYAAAAAAAAAAAAAAAAAAEAAAEAu
cGRhdGEAAEwCAAAAUAAAAAQAAAA0AAAAAAAAAAAAAAAAAABAAABALnhkYXRhAADYAQAAAGAAAAAC
AAAAOAAAAAAAAAAAAAAAAAAAQAAAQC5ic3MAAAAAoAEAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIAAAMAuaWRhdGEAAMAHAAAAgAAAAAgAAAA6AAAAAAAAAAAAAAAAAABAAADALkNSVAAAAABgAAAA
AJAAAAACAAAAQgAAAAAAAAAAAAAAAAAAQAAAwC50bHMAAAAAEAAAAACgAAAAAgAAAEQAAAAAAAAA
AAAAAAAAAEAAAMAucnNyYwAAABAXAAAAsAAAABgAAABGAAAAAAAAAAAAAAAAAABAAADALnJlbG9j
AACEAAAAANAAAAACAAAAXgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMNm
Zi4PH4QAAAAAAA8fQABIg+woSIsFtTcAADHJxwABAAAASIsFtjcAAMcAAQAAAEiLBbk3AADHAAEA
AABIiwUsNwAAZoE4TVp1D0hjUDxIAdCBOFBFAAB0ZkiLBV83AACJDblfAACLAIXAdEO5AgAAAOiB
HAAA6PQbAABIixU9OAAAixKJEOj0GwAASIsVDTgAAIsSiRDoBAwAAEiLBX02AACDOAF0UDHASIPE
KMOQuQEAAADoPhwAAOu7Dx9AAA+3UBhmgfoLAXRFZoH6CwJ1iIO4hAAAAA4Phnv///+LkPgAAAAx
yYXSD5XB6Wn///8PH4AAAAAASIsN4TcAAOgMEwAAMcBIg8Qoww8fRAAAg3h0Dg+GQP///0SLgOgA
AAAxyUWFwA+Vweks////ZpBIg+w4SIsFtTcAAEyNBeZeAABIjRXnXgAASI0N6F4AAIsAiQXAXgAA
SIsFUTcAAESLCEiNBa9eAABIiUQkIOh1GwAAkEiDxDjDDx+AAAAAAEFUVVdWU0iB7JAAAAC5DQAA
ADHASI1UJCBIidfzSKtIiz0aNgAARIsPRYXJD4WeAgAAZUiLBCUwAAAASIsdfjYAAEiLcAgx7UyL
JblwAADrGA8fgAAAAABIOcYPhA8CAAC56AMAAEH/1EiJ6PBID7EzSIXAdeJIizVTNgAAMe2LBoP4
AQ+E/QEAAIsGhcAPhGwCAADHBf5dAAABAAAAiwaD+AEPhPMBAACF7Q+EDAIAAEiLBSg1AABIiwBI
hcB0DEUxwLoCAAAAMcn/0OgfDgAASIsNeDYAAP8VInAAAEiLFZs1AABIjQ2U/f//SIkC6DwaAADo
BwwAAEiLBfA0AABIiQWJXQAA6AQaAAAxyUiLAEiFwHUc61gPH4QAAAAAAITSdEWD4QF0J7kBAAAA
SIPAAQ+2EID6IH7mQYnIQYPwAYD6IkEPRMjr5GYPH0QAAITSdBUPH0AAD7ZQAUiDwAGE0nQFgPog
fu9IiQUYXQAARIsHRYXAdBa4CgAAAPZEJFwBD4XYAAAAiQXyHAAAix0kXQAARI1jAU1j5EnB5ANM
ieHoURoAAEiLPQJdAABIicWF2w+OZQEAAEmD7Agx25BIiwwf6EcaAABIjXABSInx6CMaAABJifBI
iUQdAEiLFB9IicFIg8MI6BMaAABMOeN1zkgB60jHAwAAAABIiS2tXAAA6PgIAABIiwXxMwAATIsF
klwAAIsNnFwAAEiLAEyJAEiLFYdcAADoohoAAIsNbFwAAIkFalwAAIXJD4TkAAAAixVUXAAAhdIP
hJAAAABIgcSQAAAAW15fXUFcw2aQD7dEJGDpHv///2YPH0QAAEiLNVk0AAC9AQAAAIsGg/gBD4UD
/v//uR8AAADo9xgAAIsGg/gBD4UN/v//SIsVTTQAAEiLDTY0AADo6RgAAMcGAgAAAIXtD4X0/f//
McBIhwPp6v3//2YPH4QAAAAAAEiJ0f8VB24AAOlU/f//ZpDoqxgAAIsFuVsAAEiBxJAAAABbXl9d
QVzDDx+AAAAAAEiLFQk0AABIiw3yMwAAxwYBAAAA6H8YAADpgP3//0iJw+nP/v//icHomxgAAJBm
kEiD7ChIiwUFMwAAxwABAAAA6Lr8//+QkEiDxCjDDx8ASIPsKEiLBeUyAADHAAAAAADomvz//5CQ
SIPEKMMPHwBIg+wo6CcYAABIg/gBGcBIg8Qow5CQkJCQkJCQkJCQkEiNDQkAAADp1P///w8fQADD
kJCQkJCQkJCQkJCQkJCQSIPsKP8VDm0AADHSg/j/dAvB6ASD8AGD4AGJwonQSIPEKMNmZi4PH4QA
AAAAAGaQVbjoEAAAV1ZT6MIWAABIKcRIictIidb/FctsAACD+P90BKgQdBIxwEiBxOgQAABbXl9d
ww8fQABIjawk4AAAAEmJ2boACAAASIl0JCBMjQVMKgAASInpSI18JHj/FVZtAAAxwLkMAAAAZg/v
wEjHRCR0AAAAAEiNVCRwRTHJRTHASMeEJNAAAAAAAAAA80irSI1EJFBIiVQkQEiJ6sdEJHBoAAAA
SMdEJGAAAAAASIlEJEhIx0QkOAAAAABIx0QkMAAAAADHRCQoAAAAAMdEJCAAAAAADxFEJFD/Fehr
AACFwA+EPv///0iLTCRQSIsdzGsAAP/TSItMJFj/07gBAAAA6SH///9mDx+EAAAAAABBV0FWQVVB
VFVXVlNIgexYCAAAQbgEAQAASI1cJDBIic+J1THJSIna/xW6awAAhcB1HjHASIHEWAgAAFteX11B
XEFdQV5BX8MPH4QAAAAAALpcAAAASInZ6OsWAABIhcB00DHSTI2kJEACAABJidlMiz0ybAAATI01
0SkAAGaJEEyNBaEpAABMieG6BAEAAEH/10yLLRdsAABMifJMieFB/9VIicZIhcAPhMIAAABIjZwk
UAQAAEyNJckpAADrEZBMieJIidnoZRYAAEiFwHUoSYnwugAEAABIidnoCBYAAEiFwHXbSInx6PMV
AADpQP///2YPH0QAAA+2CEiJwoD5DXcNScfA/tv//0kPo8hzI0nHwP7b//9mDx+EAAAAAAAPtkoB
SIPCAYD5DXfzSQ+jyHLtxgIAQbn/////SYnAMdK56f0AAIlsJChIiXwkIP8Vs2oAAEiJ8eiDFQAA
uAEAAADpzf7//2YPH4QAAAAAAEmJ2UyNBe4oAAC6BAEAAEyJ4UH/10yJ8kyJ4UH/1UiJxkiFwA+E
mP7//+kP////kEFXuBgVAABBVkFVQVRVV1ZT6AoUAABIKcRIjRXQKAAASI20JBAFAABMicNBuAAE
AABIifHoZxUAAEiF23QSSInZ6DoVAABIg/gHD4foAQAASI2cJBANAAC6AAQAAEiJ2ej7/f//hcAP
hUsCAABIjZwk8AAAAEyNLQYpAABIiy2taQAAQbgEAQAASInaTInp/9WFwA+F3wEAAEyLJWhqAABM
jTX5KAAAQbgEAQAASInaTInx/9WFwHQwSI28JAADAAC6BAEAAEmJ2UiJ+UyNBfUoAABB/9RIifJI
ifnob/z//4XAD4U2AQAAQbgEAQAASInaSI0NHykAAP/VhcB0MEiNvCQAAwAAugQBAABJidlIiflM
jQWvKAAAQf/USInySIn56Cn8//+FwA+F8AAAADHAuQwAAABMjVQkYEmJ8WYP78BMjQXvKAAASI28
JIgAAABIx4QkhAAAAAAAAAC6AAQAAEyNvCSAAAAASMeEJOAAAAAAAAAA80irSI28JBANAABMiVQk
WEiJ+Q8RRCRgx4QkgAAAAGgAAABIx0QkcAAAAABB/9RMi1QkWEUxyUUxwDHJTIl8JEBIifpMiVQk
SEjHRCQ4AAAAAEjHRCQwAAAAAMdEJCgAAAAAx0QkIAAAAAD/FTFoAACFwA+F4QAAAEUxyTHJx0Qk
KAEAAABJifBIx0QkIAAAAABIjRWDKAAA/xWTaQAASIP4IA+O0QAAADHASIHEGBUAAFteX11BXEFd
QV5BX8MPHwBIjRWnJgAASInZ6EkTAABIhcAPhAD+///HRCQoAAQAAEmJ2DHSMclIiXQkIEG5////
//8V+GcAAOn4/f//Dx8ASI28JAADAAC6BAEAAEmJ2UyLJXloAABIiflMjQUvJwAAQf/USInySIn5
6Kn6//+FwA+E8f3//+lr////Dx9AAEG4AAQAAEiJ2kiJ8ejXEgAA6Z/9//9mkEiLTCRgSIsdNGcA
AP/TSItMJGj/0+k1////Zg8fRAAAQbgEAQAASInaTInx/9WFwHQwSI28JAADAAC6BAEAAEmJ2UiJ
+UyNBYQnAABB/9RIifJIifnoJvr//4XAD4Xt/v//QbgEAQAASInaTInp/9WFwHQwSI28JAADAAC6
BAEAAEmJ2UiJ+UyNBUInAABB/9RIifJIifno5Pn//4XAD4Wr/v//QbkQAAAATI0FdycAAEiNFaAn
AAAxyf8VKGgAALgBAAAA6Yf+//+QkJCQkJD/JQJoAACQkA8fhAAAAAAA/yUCaAAAkJAPH4QAAAAA
AEiD7ChIiwU1FAAASIsASIXAdCIPH0QAAP/QSIsFHxQAAEiNUAhIi0AISIkVEBQAAEiFwHXjSIPE
KMNmDx9EAABWU0iD7ChIixUTKwAASIsCicGD+P90OYXJdCCJyIPpAUiNHMJIKchIjXTC+A8fQAD/
E0iD6whIOfN19UiNDX7///9Ig8QoW17pk/j//w8fADHAZg8fRAAARI1AAYnBSoM8wgBMicB18Out
Zg8fRAAAiwW6UwAAhcB0BsMPH0QAAMcFplMAAAEAAADpcf///5AxwMOQkJCQkJCQkJCQkJCQSIPs
KIP6A3QXhdJ0E7gBAAAASIPEKMNmDx+EAAAAAADoWwoAALgBAAAASIPEKMOQVlNIg+woSIsFIyoA
AIM4AnQGxwACAAAAg/oCdBOD+gF0TrgBAAAASIPEKFtew2aQSI0dQXMAAEiNNTpzAABIOd503w8f
RAAASIsDSIXAdAL/0EiDwwhIOd517bgBAAAASIPEKFtew2YPH4QAAAAAAOjbCQAAuAEAAABIg8Qo
W17DZmYuDx+EAAAAAAAPH0AAMcDDkJCQkJCQkJCQkJCQkFZTSIPseA8RdCRADxF8JFBEDxFEJGCD
OQYPh80AAACLAUiNFbwnAABIYwSCSAHQ/+APH4AAAAAASI0doCYAAPJEDxBBIPIPEHkY8g8QcRBI
i3EIuQIAAADo4w4AAPJEDxFEJDBJidhIjRVKJwAA8g8RfCQoSInBSYnx8g8RdCQg6FsPAACQDxB0
JEAPEHwkUDHARA8QRCRgSIPEeFtew5BIjR0ZJgAA65YPH4AAAAAASI0daSYAAOuGDx+AAAAAAEiN
HTkmAADpc////w8fQABIjR2ZJgAA6WP///8PH0AASI0dYSYAAOlT////SI0dsyYAAOlH////kJCQ
kJCQkJDb48OQkJCQkJCQkJCQkJCQVlNIg+w4SInLSI1EJFi5AgAAAEiJVCRYTIlEJGBMiUwkaEiJ
RCQo6AQOAABBuBsAAAC6AQAAAEiNDbImAABJicHomg4AAEiLdCQouQIAAADo2w0AAEiJ2kiJwUmJ
8Oi1DgAA6EAOAACQDx+AAAAAAFdWU0iD7FBIYzWmUQAASInLhfYPjhcBAABIiwWYUQAARTHJSIPA
GGYPH4QAAAAAAEyLAEw5w3ITSItQCItSCEkB0Ew5ww+CigAAAEGDwQFIg8AoQTnxddhIidno8AkA
AEiJx0iFwA+E5gAAAEiLBUVRAABIjRy2SMHjA0gB2EiJeCDHAAAAAADoAwsAAItXDEG4MAAAAEiN
DBBIiwUXUQAASI1UJCBIiUwYGP8V72IAAEiFwA+EfQAAAItEJESNUMCD4r90CI1Q/IPi+3USgwXf
UAAAAUiDxFBbXl/DDx8Ag/gCSItMJCBIi1QkOEG4QAAAALgEAAAARA9EwEgDHbVQAABIiUsISYnZ
SIlTEP8VhGIAAIXAdbb/FTJiAABIjQ3TJQAAicLoZP7//w8fQAAx9ukh////SIsFelAAAItXCEiN
DXglAABMi0QYGOg+/v//SInaSI0NRCUAAOgv/v//kGZmLg8fhAAAAAAADx8AVUFXQVZBVUFUV1ZT
SIPsSEiNbCRARIslJFAAAEWF5HQXSI1lCFteX0FcQV1BXkFfXcNmDx9EAADHBf5PAAABAAAA6BkJ
AABImEiNBIBIjQTFDwAAAEiD4PDoYgsAAEyLLWsmAABIix10JgAAxwXOTwAAAAAAAEgpxEiNRCQw
SIkFw08AAEyJ6Egp2EiD+Ad+kIsTSIP4Cw+PewEAAIsDhcAPhWkCAACLQwSFwA+FXgIAAItTCIP6
AQ+FkAIAAEiDwwxMOesPg1b///9MizUuJgAASb////9//////+tUZpAPtjeB4cAAAABAhPYPiQYC
AABIgc4A////SCnGTAHOhcl1F0iB/v8AAAAPj08BAABIg/6AD4xFAQAASIn56G79//9AiDdIg8MM
TDnrD4OOAAAAiwOLSwiLewRMAfAPttFMiwhMAfeD+iAPhCkBAAAPh+sAAACD+gh0hoP6EA+F3wEA
AA+3N4HhwAAAAGaF9g+JawEAAEiBzgAA//9IKcZMAc6FyXUaSIH+AID//w+MzAAAAEiB/v//AAAP
j78AAABIiflIg8MM6OT8//9miTdMOesPgnr///8PH4QAAAAAAIsVfk4AAIXSD45T/v//SIs1U2AA
ADHbSI19/A8fRAAASIsFYU4AAEgB2ESLAEWFwHQNSItQEEiLSAhJifn/1kGDxAFIg8MoRDslNk4A
AHzQ6Qz+//8PHwCF0g+F8AAAAItDBInCC1MID4V8/v//SIPDDOlm/v//Zg8fhAAAAAAAg/pAD4X5
AAAASIs3SCnGTAHOgeHAAAAAdWZIhfZ4YUiJdCQgSYn4SI0NqiMAAOit+///Dx9EAACLN4HhwAAA
AIX2eUxJuwAAAAD/////TAneSCnGTAHOhcl1D0w5/n6/uP////9IOcZ/tUiJ+eje+///iTfpbP7/
/w8fgAAAAABIifnoyPv//0iJN+lV/v//SCnGTAHOhcl0wevODx9AAEgpxkwBzoXJD4SY/v//6a3+
//8PH0QAAEgpxkwBzoXJD4T9/f//6Q/+//8PH0QAAEw56w+DCP3//0yLNeAjAACLcwSLO0iDwwhM
AfYDPkiJ8eha+///iT5MOety4+l+/v//SI0NnyIAAOjS+v//SI0NWyIAAOjG+v//kJCQkJCQSIPs
WEiLBeVMAABmDxTTSIXAdCXyDxCEJIAAAACJTCQgSI1MJCBIiVQkKA8RVCQw8g8RRCRA/9CQSIPE
WMNmkEiJDalMAADp5AgAAJCQkJBTSIPsIEiLEYsCSInLicGB4f///yCB+UNDRyAPhJ8AAAA9lgAA
wHd3PYsAAMB2IQVz//8/g/gJd1RIjRWAIgAASGMEgkgB0P/gDx+AAAAAAD0FAADAD4TVAAAAdjs9
CAAAwHQpPR0AAMB1NDHSuQQAAADo8QgAAEiD+AEPhNYAAABIhcB0GbkEAAAA/9C4/////0iDxCBb
wz0CAACAdO5IiwUaTAAASIXAdCVIidlIg8QgW0j/4GYuDx+EAAAAAAD2QgQBD4VX////68EPH0AA
McBIg8QgW8MPH4QAAAAAADHSuQgAAADofAgAAEiD+AEPhIkAAABIhcB0pLkIAAAA/9DriQ8fQAAx
0rkIAAAA6FQIAABIg/gBddy6AQAAALkIAAAA6D8IAADpX////2aQMdK5CwAAAOgsCAAASIP4AXQp
SIXAD4RU////uQsAAAD/0Ok2////ugEAAAC5BAAAAOgCCAAA6SL///+6AQAAALkLAAAA6O4HAADp
Dv///7oBAAAAuQgAAADo2gcAAOjN+P//6fX+//+QkJCQkJCQkEFUVVdWU0iD7CBMjSVPSwAATInh
/xVeXAAASIsdH0sAAEiF23Q2SIsto1wAAEiLPVxcAAAPH0AAiwv/1UiJxv/XhcB1DkiF9nQJSItD
CEiJ8f/QSItbEEiF23XcTInhSIPEIFteX11BXEj/JUBcAABXVlNIg+wgiwXLSgAAic9IidaFwHUK
McBIg8QgW15fw7oYAAAAuQEAAADo4QYAAEiJw0iFwHQzSIlwCEiNNa5KAACJOEiJ8f8Vu1sAAEiL
BXxKAABIifFIiR1ySgAASIlDEP8V2FsAAOusg8j/66mQVlNIg+woiwVcSgAAicuFwHUOMcBIg8Qo
W17DDx9EAABIjTVZSgAASInx/xVoWwAASIsNKUoAAEiFyXQnMdLrC0iJykiFwHQbSInBiwE52EiL
QRB160iF0nQeSIlCEOhlBgAASInx/xVkWwAAMcBIg8QoW17DDx8ASIkF4UkAAOvdZmYuDx+EAAAA
AAAPH0AAU0iD7CCD+gIPhLIAAAB3MIXSdEyLBb5JAACFwA+EvgAAAMcFrEkAAAEAAAC4AQAAAEiD
xCBbw2YPH4QAAAAAAIP6A3XniwWNSQAAhcB03eg8/v//69ZmLg8fhAAAAAAAiwVySQAAhcB1ZosF
aEkAAIP4AXW3SIsdVEkAAEiF23QYDx+AAAAAAEiJ2UiLWxDopAUAAEiF23XvSI0NUEkAAEjHBSVJ
AAAAAAAAxwUjSQAAAAAAAP8VRVoAAOls////6Iv2//+4AQAAAEiDxCBbw+i7/f//65NmDx+EAAAA
AABIjQ0JSQAA/xVLWgAA6TD///+QkJCQkJCQkJCQkJCQkDHAZoE5TVp1D0hjUTxIAdGBOVBFAAB0
CMMPH4AAAAAAMcBmgXkYCwIPlMDDDx9AAEhjQTxIAcEPt0EURA+3QQZIjUQBGGZFhcB0MkGNSP9I
jQyJTI1MyCgPH4QAAAAAAESLQAxMicFMOcJyCANICEg5ynILSIPAKEw5yHXjMcDDV1ZTSIPsIEiJ
zujRBAAASIP4CHd7SIsVpB4AADHbZoE6TVp1WUhjQjxIAdCBOFBFAAB1SmaBeBgLAnVCD7dQFEiN
XBAYD7dQBmaF0nRCjUL/SI0EgEiNfMMo6w0PH0AASIPDKEg5+3QnQbgIAAAASInySInZ6G4EAACF
wHXiSInYSIPEIFteX8MPH4AAAAAAMdtIidhIg8QgW15fww8fAEiLFRkeAAAxwGaBOk1adRBMY0I8
SQHQQYE4UEUAAHQIww8fgAAAAABmQYF4GAsCde9BD7dAFEgp0UmNRAAYRQ+3QAZmRYXAdDRBjVD/
SI0UkkyNTNAoZi4PH4QAAAAAAESLQAxMicJMOcFyCANQCEg50XKsSIPAKEw5yHXjMcDDSIsFmR0A
ADHJZoE4TVp1D0hjUDxIAdCBOFBFAAB0CYnIw2YPH0QAAGaBeBgLAnXvD7dIBonIw2YPH4QAAAAA
AEyLBVkdAAAxwGZBgThNWnUPSWNQPEwBwoE6UEUAAHQIww8fgAAAAABmgXoYCwJ18A+3QhRED7dC
BkiNRAIYZkWFwHQsQY1Q/0iNFJJIjVTQKA8fgAAAAAD2QCcgdAlIhcl0vUiD6QFIg8AoSDnQdegx
wMNmZi4PH4QAAAAAAGaQSIsF2RwAADHSZoE4TVp1D0hjSDxIAcGBOVBFAAB0CUiJ0MMPH0QAAGaB
eRgLAkgPRNBIidDDZi4PH4QAAAAAAEiLFZkcAAAxwGaBOk1adRBMY0I8SQHQQYE4UEUAAHQIww8f
gAAAAABmQYF4GAsCde9IKdFFD7dIBkEPt1AUSY1UEBhmRYXJdNdBjUH/SI0EgEyNTMIoZi4PH4QA
AAAAAESLQgxMicBMOcFyCANCCEg5wXIMSIPCKEk50XXjMcDDi0Ik99DB6B/DDx+AAAAAAEyLHQkc
AABFMclmQYE7TVp1EE1jQzxNAdhBgThQRQAAdA5MicjDZi4PH4QAAAAAAGZBgXgYCwJ16UGLgJAA
AACFwHTeQQ+3UBRFD7dQBkmNVBAYZkWF0nTJRY1C/0+NBIBOjVTCKGYuDx+EAAAAAABEi0oMTYnI
TDnIcglEA0IITDnAchNIg8IoTDnSdeJFMclMicjDDx8ATAHY6woPHwCD6QFIg8AURItABEWFwHUH
i1AMhdJ014XJf+VEi0gMTQHZTInIw5CQkJCQkJCQkJBRUEg9ABAAAEiNTCQYchlIgekAEAAASIMJ
AEgtABAAAEg9ABAAAHfnSCnBSIMJAFhZw5CQkJCQkJCQkJCQkJCQSIsFORsAAEiLAMOQkJCQkEiL
BRkbAABIiwDDkJCQkJBIiwX5GgAASIsAw5CQkJCQSIsF6UQAAMMPH4QAAAAAAEiJyEiHBdZEAADD
kJCQkJBTSIPsIInL6CQAAACJ2UiNFElIweIESAHQSIPEIFvDkP8lylUAAJCQ/yXKVQAAkJD/JdJV
AACQkP8l0lUAAJCQ/yXSVQAAkJD/JdpVAACQkP8l2lUAAJCQ/yXqVQAAkJD/JepVAACQkP8l6lUA
AJCQ/yXqVQAAkJD/JepVAACQkP8l6lUAAJCQ/yXqVQAAkJD/JepVAACQkP8l6lUAAJCQ/yXqVQAA
kJD/JepVAACQkP8l6lUAAJCQ/yXqVQAAkJD/JepVAACQkP8l6lUAAJCQ/yXqVQAAkJD/JepVAACQ
kP8l6lUAAJCQ/yXqVQAAkJD/JepVAACQkP8l6lUAAJCQ/yXaVAAAkJD/JcpUAACQkP8lulQAAJCQ
/yWqVAAAkJD/JZpUAACQkP8lilQAAJCQ/yV6VAAAkJD/JWpUAACQkP8lWlQAAJCQ/yVKVAAAkJD/
JTpUAACQkP8lKlQAAJCQ/yUaVAAAkJD/JQpUAACQkP8l+lMAAJCQ/yXqUwAAkJD/JdpTAACQkA8f
hAAAAAAASIPsKOgn7v//SIsFsBkAADHSSIsISIsFxBkAAESLCEiLBaoZAABMiwBIg8Qo6Y7p//+Q
kJCQkJCQkJCQkJCQkOl75v//kJCQkJCQkJCQkJD//////////5AuAEABAAAAAAAAAAAAAAD/////
/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAMAu
AEABAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAA
AAAAAABwLABAAQAAAAAAAAAAAAAAgCwAQAEAAAAAAAAAAAAAAJAsAEABAAAAAAAAAAAAAACgLABA
AQAAALAsAEABAAAAwCwAQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiACUAcwAiACAALQAtAGEAcABw
AD0AIgAlAHMAIgAgAC0ALQB3AGkAbgBkAG8AdwAtAHMAaQB6AGUAPQAxADIAOAAwACwAOAA0ADAA
IAAtAC0AZQBuAGEAYgBsAGUALQBmAGUAYQB0AHUAcgBlAHMAPQBPAHYAZQByAGwAYQB5AFMAYwBy
AG8AbABsAGIAYQByAAAAAAAAACUAcwBcAHMAdQBuAGYAeQBlAHIAXwB1AHIAbAAuAHQAeAB0AAAA
cgAsACAAYwBjAHMAPQBVAFQARgAtADgAAAAlAHMAXABTAHUAbgBmAHkAZQByAC4AdQByAGwAAABo
dHRwAAAAAAAAaAB0AHQAcABzADoALwAvAGEAaQBzAC0AZABlAHYALQBxAG8AZQA1AGUAbAB3AHAA
MwAzAHoAbgBoAGUAZgBsAHUAMwBiAGMAdQBmAC0ANQA1ADcAMQAzADcAOAA4ADUANQA5ADYALgBl
AHUAcgBvAHAAZQAtAHcAZQBzAHQAMgAuAHIAdQBuAC4AYQBwAHAAAABQAHIAbwBnAHIAYQBtAEYA
aQBsAGUAcwAAAAAAAABQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwAoAHgAOAA2ACkAAAAAAAAAJQBz
AFwARwBvAG8AZwBsAGUAXABDAGgAcgBvAG0AZQBcAEEAcABwAGwAaQBjAGEAdABpAG8AbgBcAGMA
aAByAG8AbQBlAC4AZQB4AGUAAABMAE8AQwBBAEwAQQBQAFAARABBAFQAQQAAAAAAAAAAAGMAaABy
AG8AbQBlAC4AZQB4AGUAIAAtAC0AYQBwAHAAPQAiACUAcwAiACAALQAtAHcAaQBuAGQAbwB3AC0A
cwBpAHoAZQA9ADEAMgA4ADAALAA4ADQAMAAAAG8AcABlAG4AAAAAAAAAJQBzAFwATQBpAGMAcgBv
AHMAbwBmAHQAXABFAGQAZwBlAFwAQQBwAHAAbABpAGMAYQB0AGkAbwBuAFwAbQBzAGUAZABnAGUA
LgBlAHgAZQAAAAAAAAAAAFMAdQBuAGYAeQBlAHIAIABBAEkAIABBAHMAcwBpAHMAdABhAG4AdAAA
AAAAAAAAAFUAbgBhAGIAbABlACAAdABvACAAbABhAHUAbgBjAGgAIABiAHIAbwB3AHMAZQByACAA
ZgBvAHIAIABTAHUAbgBmAHkAZQByACAAQQBJACAAQQBzAHMAaQBzAHQAYQBuAHQALgAgAFAAbABl
AGEAcwBlACAAbwBwAGUAbgAgAEcAbwBvAGcAbABlACAAQwBoAHIAbwBtAGUALgAAAAAAAAAAAAAA
AAAAAOAcAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAQAEAAAAIoABAAQAAAIxwAEAB
AAAAOJAAQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFyZ3VtZW50IGRvbWFp
biBlcnJvciAoRE9NQUlOKQBBcmd1bWVudCBzaW5ndWxhcml0eSAoU0lHTikAAAAAAABPdmVyZmxv
dyByYW5nZSBlcnJvciAoT1ZFUkZMT1cpAFBhcnRpYWwgbG9zcyBvZiBzaWduaWZpY2FuY2UgKFBM
T1NTKQAAAABUb3RhbCBsb3NzIG9mIHNpZ25pZmljYW5jZSAoVExPU1MpAAAAAAAAVGhlIHJlc3Vs
dCBpcyB0b28gc21hbGwgdG8gYmUgcmVwcmVzZW50ZWQgKFVOREVSRkxPVykAVW5rbm93biBlcnJv
cgAAAAAAX21hdGhlcnIoKTogJXMgaW4gJXMoJWcsICVnKSAgKHJldHZhbD0lZykKAAAI2f//vNj/
/1TY///c2P//7Nj///zY///M2P//TWluZ3ctdzY0IHJ1bnRpbWUgZmFpbHVyZToKAAAAAABBZGRy
ZXNzICVwIGhhcyBubyBpbWFnZS1zZWN0aW9uACAgVmlydHVhbFF1ZXJ5IGZhaWxlZCBmb3IgJWQg
Ynl0ZXMgYXQgYWRkcmVzcyAlcAAAAAAAAAAAICBWaXJ0dWFsUHJvdGVjdCBmYWlsZWQgd2l0aCBj
b2RlIDB4JXgAACAgVW5rbm93biBwc2V1ZG8gcmVsb2NhdGlvbiBwcm90b2NvbCB2ZXJzaW9uICVk
LgoAAAAAAAAAICBVbmtub3duIHBzZXVkbyByZWxvY2F0aW9uIGJpdCBzaXplICVkLgoAAAAAAAAA
JWQgYml0IHBzZXVkbyByZWxvY2F0aW9uIGF0ICVwIG91dCBvZiByYW5nZSwgdGFyZ2V0aW5nICVw
LCB5aWVsZGluZyB0aGUgdmFsdWUgJXAuCgAAAAAAACDe//8g3v//IN7//yDe//8g3v//zd3//yDe
//9I3v//zd3//6vd//8AAAAAAAAAADAwAEABAAAAAAAAAAAAAABAMABAAQAAAAAAAAAAAAAAoC4A
QAEAAAAAAAAAAAAAAOBMAEABAAAAAAAAAAAAAADgTABAAQAAAAAAAAAAAAAA4EMAQAEAAAAAAAAA
AAAAAAAAAEABAAAAAAAAAAAAAADAggBAAQAAAAAAAAAAAAAA4IIAQAEAAAAAAAAAAAAAAPiCAEAB
AAAAAAAAAAAAAAAAgwBAAQAAAAAAAAAAAAAAoHAAQAEAAAAAAAAAAAAAAIhwAEABAAAAAAAAAAAA
AACEcABAAQAAAAAAAAAAAAAAgHAAQAEAAAAAAAAAAAAAAOBwAEABAAAAAAAAAAAAAAAQcABAAQAA
AAAAAAAAAAAACHAAQAEAAAAAAAAAAAAAAAAwAEABAAAAAAAAAAAAAABQcABAAQAAAAAAAAAAAAAA
WHAAQAEAAAAAAAAAAAAAAACQAEABAAAAAAAAAAAAAAAQkABAAQAAAAAAAAAAAAAAGJAAQAEAAAAA
AAAAAAAAACiQAEABAAAAAAAAAAAAAACQcABAAQAAAAAAAAAAAAAAYHAAQAEAAAAAAAAAAAAAANBw
AEABAAAAAAAAAAAAAAAgJABAAQAAAAAAAAAAAAAAgB0AQAEAAAAAAAAAAAAAAHBwAEABAAAAAAAA
AAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTItd2luMzIA
AAAAAAAAAAAAAAAAR0NDOiAoR05VKSAxMi13aW4zMgAAAAAAAAAAAAAAAABHQ0M6IChHTlUpIDEy
IDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAo
R05VKSAxMiAyMDIyMDgxOQAAAAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAAAAAA
AEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIyMDgxOQAA
AAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTIgMjAy
MjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIyMDgxOQAAAAAAAAAAAABHQ0M6IChHTlUp
IDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAAR0ND
OiAoR05VKSAxMiAyMDIyMDgxOQAAAAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAA
AAAAAEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIyMDgx
OQAAAAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTIg
MjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIyMDgxOQAAAAAAAAAAAABHQ0M6IChH
TlUpIDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAA
R0NDOiAoR05VKSAxMi13aW4zMgAAAAAAAAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAA
AAAAAAAAAEdDQzogKEdOVSkgMTIgMjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIy
MDgxOQAAAAAAAAAAAABHQ0M6IChHTlUpIDEyIDIwMjIwODE5AAAAAAAAAAAAAEdDQzogKEdOVSkg
MTIgMjAyMjA4MTkAAAAAAAAAAAAAR0NDOiAoR05VKSAxMiAyMDIyMDgxOQAAAAAAAAAAAABHQ0M6
IChHTlUpIDEyLXdpbjMyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABEAAAAGAAABAQAAAuEQAABGAAADAR
AAB5EQAADGAAAIARAACuFAAAFGAAALAUAADNFAAAKGAAANAUAADtFAAASGAAAPAUAAAEFQAAaGAA
ABAVAAAcFQAAcGAAACAVAAAhFQAAdGAAADAVAABTFQAAeGAAAGAVAABnFgAAgGAAAHAWAAAPGAAA
kGAAABAYAACqGwAAqGAAANAbAAAKHAAAyGAAABAcAAB6HAAA0GAAAIAcAACfHAAA3GAAAKAcAACj
HAAA4GAAALAcAADfHAAA5GAAAOAcAABhHQAA7GAAAHAdAABzHQAA+GAAAIAdAAB4HgAA/GAAAIAe
AACDHgAAFGEAAJAeAAD5HgAAGGEAAAAfAABiIAAAJGEAAHAgAADLIwAAMGEAANAjAAAOJAAASGEA
ABAkAAAcJAAAUGEAACAkAAC4JQAAVGEAAMAlAAAwJgAAXGEAADAmAACfJgAAbGEAAKAmAAAhJwAA
eGEAADAnAAAiKAAAhGEAADAoAABcKAAAjGEAAGAoAACwKAAAkGEAALAoAABNKQAAlGEAAFApAADQ
KQAAoGEAANApAAAHKgAApGEAABAqAACDKgAAqGEAAJAqAADGKgAArGEAANAqAABZKwAAsGEAAGAr
AAAmLAAAtGEAAHAsAAB7LAAAuGEAAIAsAACLLAAAvGEAAJAsAACbLAAAwGEAAKAsAACoLAAAxGEA
ALAsAAC7LAAAyGEAAMAsAADfLAAAzGEAAFAuAACCLgAAwGAAAJAuAACVLgAA1GEAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQQBAARCAAABBAEABGIAAAENBwANARIA
BjAFYARwA1ACwAAACQQBAARCAADgLAAAAQAAALQUAADHFAAAICQAAMcUAAAJBAEABEIAAOAsAAAB
AAAA1BQAAOcUAAAgJAAA5xQAAAEEAQAEQgAAAQAAAAEAAAABBAEABEIAAAERBgARAR0CCTAIYAdw
AVABEwoAEwELAQwwC2AKcAlQCMAG0ATgAvABGQoAGQGjAhEwEGAPcA5QDcAL0AngAvABBAEABEIA
AAEEAQAEQgAAAQYDAAZCAjABYAAAAQAAAAEAAAABBAEABEIAAAEGAwAGQgIwAWAAAAEAAAABFgkA
FogGABB4BQALaAQABuICMAFgAAABAAAAAQYDAAZiAjABYAAAAQcEAAeSAzACYAFwARUKRRUDEIIM
MAtgCnAJwAfQBeAD8AFQAQQBAASiAAABAAAAAQUCAAUyATABCgYACjIGMAVgBHADUALAAQcEAAcy
AzACYAFwAQYDAAZCAjABYAAAAQUCAAUyATABAAAAAQAAAAEHBAAHMgMwAmABcAEAAAABAAAAAQAA
AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQUCAAUyATABAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGiAAAAAAAAAAAAAAASHAAAgggAA+IAAAAAAAAAA
AAAAlIcAALCCAAAAggAAAAAAAAAAAACkhwAAuIMAABCCAAAAAAAAAAAAALSHAADIgwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA2IMAAAAAAADmgwAAAAAAAPiDAAAAAAAAEIQAAAAAAAAohAAAAAAA
AEKEAAAAAAAAWIQAAAAAAABohAAAAAAAAH6EAAAAAAAAkIQAAAAAAACshAAAAAAAAMSEAAAAAAAA
2oQAAAAAAAD4hAAAAAAAAACFAAAAAAAADoUAAAAAAAAghQAAAAAAAAAAAAAAAAAAMIUAAAAAAABI
hQAAAAAAAFiFAAAAAAAAZIUAAAAAAAByhQAAAAAAAISFAAAAAAAAmIUAAAAAAACihQAAAAAAALCF
AAAAAAAAuoUAAAAAAADGhQAAAAAAANCFAAAAAAAA3IUAAAAAAADmhQAAAAAAAPSFAAAAAAAA/oUA
AAAAAAAGhgAAAAAAABCGAAAAAAAAGIYAAAAAAAAihgAAAAAAACqGAAAAAAAANIYAAAAAAAA8hgAA
AAAAAEaGAAAAAAAAUIYAAAAAAABahgAAAAAAAGSGAAAAAAAAboYAAAAAAAB4hgAAAAAAAIKGAAAA
AAAAjoYAAAAAAACYhgAAAAAAAAAAAAAAAAAAooYAAAAAAAAAAAAAAAAAALKGAAAAAAAAAAAAAAAA
AADYgwAAAAAAAOaDAAAAAAAA+IMAAAAAAAAQhAAAAAAAACiEAAAAAAAAQoQAAAAAAABYhAAAAAAA
AGiEAAAAAAAAfoQAAAAAAACQhAAAAAAAAKyEAAAAAAAAxIQAAAAAAADahAAAAAAAAPiEAAAAAAAA
AIUAAAAAAAAOhQAAAAAAACCFAAAAAAAAAAAAAAAAAAAwhQAAAAAAAEiFAAAAAAAAWIUAAAAAAABk
hQAAAAAAAHKFAAAAAAAAhIUAAAAAAACYhQAAAAAAAKKFAAAAAAAAsIUAAAAAAAC6hQAAAAAAAMaF
AAAAAAAA0IUAAAAAAADchQAAAAAAAOaFAAAAAAAA9IUAAAAAAAD+hQAAAAAAAAaGAAAAAAAAEIYA
AAAAAAAYhgAAAAAAACKGAAAAAAAAKoYAAAAAAAA0hgAAAAAAADyGAAAAAAAARoYAAAAAAABQhgAA
AAAAAFqGAAAAAAAAZIYAAAAAAABuhgAAAAAAAHiGAAAAAAAAgoYAAAAAAACOhgAAAAAAAJiGAAAA
AAAAAAAAAAAAAACihgAAAAAAAAAAAAAAAAAAsoYAAAAAAAAAAAAAAAAAAI0AQ2xvc2VIYW5kbGUA
7wBDcmVhdGVQcm9jZXNzVwAAGwFEZWxldGVDcml0aWNhbFNlY3Rpb24APwFFbnRlckNyaXRpY2Fs
U2VjdGlvbgAATQJHZXRFbnZpcm9ubWVudFZhcmlhYmxlVwBbAkdldEZpbGVBdHRyaWJ1dGVzVwAA
dgJHZXRMYXN0RXJyb3IAAIoCR2V0TW9kdWxlRmlsZU5hbWVXAADnAkdldFN0YXJ0dXBJbmZvQQB8
A0luaXRpYWxpemVDcml0aWNhbFNlY3Rpb24A2ANMZWF2ZUNyaXRpY2FsU2VjdGlvbgAADARNdWx0
aUJ5dGVUb1dpZGVDaGFyAHIFU2V0VW5oYW5kbGVkRXhjZXB0aW9uRmlsdGVyAIIFU2xlZXAApQVU
bHNHZXRWYWx1ZQDUBVZpcnR1YWxQcm90ZWN0AADWBVZpcnR1YWxRdWVyeQAAOABfX0Nfc3BlY2lm
aWNfaGFuZGxlcgAAUgBfX2dldG1haW5hcmdzAFMAX19pbml0ZW52AFQAX19pb2JfZnVuYwAAYQBf
X3NldF9hcHBfdHlwZQAAYwBfX3NldHVzZXJtYXRoZXJyAAByAF9hY21kbG4AeQBfYW1zZ19leGl0
AACLAF9jZXhpdAAAlwBfY29tbW9kZQAA3ABfZm1vZGUAABsBX2luaXR0ZXJtACcCX29uZXhpdACh
BF9zbndwcmludGYAADsDX3dmb3BlbgCFA2Fib3J0AJYDY2FsbG9jAACjA2V4aXQAAKcDZmNsb3Nl
AACtA2ZnZXRzALcDZnByaW50ZgC+A2ZyZWUAAMsDZndyaXRlAAD6A21hbGxvYwAAAgRtZW1jcHkA
ACIEc2lnbmFsAAA5BHN0cmxlbgAAPARzdHJuY21wAEIEc3Ryc3RyAABeBHZmcHJpbnRmAAB8BHdj
c25jcHkAgAR3Y3NyY2hyAFQBU2hlbGxFeGVjdXRlVwBsAk1lc3NhZ2VCb3hXAACAAAAAgAAAAIAA
AACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAA
S0VSTkVMMzIuZGxsAAAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAAU
gAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSA
AAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAbXN2Y3J0LmRsbAAAKIAAAFNIRUxMMzIuZGxs
ADyAAABVU0VSMzIuZGxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEQBAAQAAAAAAAAAAAAAAAAAAAAAAAAAQ
EABAAQAAAAAAAAAAAAAAAAAAAAAAAADgHABAAQAAALAcAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwADAAAAKAAAgA4AAABYAACAGAAA
AIgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAEAAAIAAAAAAAAAAAAAAAAAAAAEACQQAALgAAAAAAAAA
AAAAAAAAAAAAAAEAAQAAAHAAAIAAAAAAAAAAAAAAAAAAAAEACQQAAMgAAAAAAAAAAAAAAAAAAAAA
AAEAAQAAAKAAAIAAAAAAAAAAAAAAAAAAAAEACQQAANgAAADosAAAqBAAAAAAAAAAAAAAkMEAABQA
AAAAAAAAAAAAAKjBAABhBQAAAAAAAAAAAAAoAAAAIAAAAEAAAAABACAAAAAAAAAQAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7BCS/+xQkv/shJL/7KiS/+zAkv/syJL/7MCS/+yok
v/shJL/7FCS/+wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7BSS/+x0kv/syJL/7RCS/+1Ikv/tcJL/7
YiS/+2Qkv/tiJL/7XCS/+1Ikv/tEJL/7MiS/+x0kv/sFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+xQkv/swJL/7SiS/+2Ak
v/tzJL/7giS/+40kv/uUJL/7liS/+5Qkv/uNJL/7giS/+3Mkv/tgJL/7SiS/+zAkv/sUAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sbJL/7
PCS/+1okv/t1JL/7jSS/+6Ekv/uyJL/7viS/+8YVzPr/JL/7xiS/+74kv/uyJL/7oSS/+40kv/t1
JL/7WiS/+zwkv/sbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAJL/7GyS/+0Akv/tiJL/7giS/+58kv/u5GM36/x/P+v8l0Pr/KNH6/ynR+v8o0fr/JdD6/x/P
+v8Yzfr/JL/7uSS/+58kv/uCJL/7YiS/+0Akv/sbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAACS/+xQkv/s8JL/7YiS/+4Ykv/uoFcz6/yDP+v8q0fr/MtP6/zjV+v881vr/
Pdb6/zzW+v841fr/MtP6/yrR+v8gz/r/Fcz6/yS/+6gkv/uGJL/7YiS/+zwkv/sUAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sFJL/7MCS/+1okv/uCJL/7qBfN+v8l0Pr/MdP6/zzW
+v9F2Pr/S9r6/1Db+v9R2/r/UNv6/0va+v9F2Pr/PNb6/zHT+v8l0Pr/F836/yS/+6gkv/uCJL/7
WiS/+zAkv/sFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+x0kv/tKJL/7dSS/+58VzPr/
JdD6/zPU+v9B1/r/Tdr6/1fd+v9f3/r/Y+D6/2Xg+v9j4Pr/X9/6/1fd+v9N2vr/Qdf6/zPU+v8l
0Pr/Fcz6/yS/+58kv/t1JL/7SiS/+x0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sEJL/7MiS/
+2Akv/uNJL/7uSDP+v8x0/r/Qdf6/1Db+v9d3vr/aOH6/3Hk+v935fr/eeb6/3fl+v9x5Pr/aOH6
/13e+v9Q2/r/Qdf6/zHT+v8gz/r/JL/7uSS/+40kv/tgJL/7MiS/+wQAAAAAAAAAAAAAAAAAAAAA
AAAAACS/+xQkv/tEJL/7cyS/+6EYzfr/KtH6/zzW+v9N2vr/Xd76/2zi+v955vr/hOj6/4vq+v+N
6/r/i+r6/4To+v955vr/bOL6/13e+v9N2vr/PNb6/yrR+v8Yzfr/JL/7oSS/+3Mkv/tEJL/7FAAA
AAAAAAAAAAAAAAAAAAAAAAAAJL/7ISS/+1Ikv/uCJL/7sh/P+v8y0/r/Rdj6/1fd+v9o4fr/eeb6
/4jp+v+V7fr/nu/6/6Hw+v+e7/r/le36/4jp+v955vr/aOH6/1fd+v9F2Pr/MtP6/x/P+v8kv/uy
JL/7giS/+1Ikv/shAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sqJL/7XCS/+40kv/u+JdD6/zjV+v9L
2vr/X9/6/3Hk+v+E6Pr/le36/6Tx+v+w9Pr/tfX6/7D0+v+k8fr/le36/4To+v9x5Pr/X9/6/0va
+v841fr/JdD6/yS/+74kv/uNJL/7XCS/+yoAAAAAAAAAAAAAAAAAAAAAAAAAACS/+zAkv/tiJL/7
lCS/+8Yo0fr/PNb6/1Db+v9j4Pr/d+X6/4vq+v+e7/r/sPT6/8H4+v/J+vr/wfj6/7D0+v+e7/r/
i+r6/3fl+v9j4Pr/UNv6/zzW+v8o0fr/JL/7xiS/+5Qkv/tiJL/7MAAAAAAAAAAAAAAAAAAAAAAk
v/sAJL/7MiS/+2Qkv/uWFcz6/ynR+v891vr/Udv6/2Xg+v955vr/jev6/6Hw+v+19fr/yfr6/93/
+v/J+vr/tfX6/6Hw+v+N6/r/eeb6/2Xg+v9R2/r/Pdb6/ynR+v8VzPr/JL/7liS/+2Qkv/syJL/7
AAAAAAAAAAAAAAAAAAAAAAAkv/swJL/7YiS/+5Qkv/vGKNH6/zzW+v9Q2/r/Y+D6/3fl+v+L6vr/
nu/6/7D0+v/B+Pr/yfr6/8H4+v+w9Pr/nu/6/4vq+v935fr/Y+D6/1Db+v881vr/KNH6/yS/+8Yk
v/uUJL/7YiS/+zAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+yokv/tcJL/7jSS/+74l0Pr/ONX6/0va
+v9f3/r/ceT6/4To+v+V7fr/pPH6/7D0+v+19fr/sPT6/6Tx+v+V7fr/hOj6/3Hk+v9f3/r/S9r6
/zjV+v8l0Pr/JL/7viS/+40kv/tcJL/7KgAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7ISS/+1Ikv/uC
JL/7sh/P+v8y0/r/Rdj6/1fd+v9o4fr/eeb6/4jp+v+V7fr/nu/6/6Hw+v+e7/r/le36/4jp+v95
5vr/aOH6/1fd+v9F2Pr/MtP6/x/P+v8kv/uyJL/7giS/+1Ikv/shAAAAAAAAAAAAAAAAAAAAAAAA
AAAkv/sUJL/7RCS/+3Mkv/uhGM36/yrR+v881vr/Tdr6/13e+v9s4vr/eeb6/4To+v+L6vr/jev6
/4vq+v+E6Pr/eeb6/2zi+v9d3vr/Tdr6/zzW+v8q0fr/GM36/yS/+6Ekv/tzJL/7RCS/+xQAAAAA
AAAAAAAAAAAAAAAAAAAAACS/+wQkv/syJL/7YCS/+40kv/u5IM/6/zHT+v9B1/r/UNv6/13e+v9o
4fr/ceT6/3fl+v955vr/d+X6/3Hk+v9o4fr/Xd76/1Db+v9B1/r/MdP6/yDP+v8kv/u5JL/7jSS/
+2Akv/syJL/7BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+x0kv/tKJL/7dSS/+58VzPr/JdD6
/zPU+v9B1/r/Tdr6/1fd+v9f3/r/Y+D6/2Xg+v9j4Pr/X9/6/1fd+v9N2vr/Qdf6/zPU+v8l0Pr/
Fcz6/yS/+58kv/t1JL/7SiS/+x0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7BSS/+zAk
v/taJL/7giS/+6gXzfr/JdD6/zHT+v881vr/Rdj6/0va+v9Q2/r/Udv6/1Db+v9L2vr/Rdj6/zzW
+v8x0/r/JdD6/xfN+v8kv/uoJL/7giS/+1okv/swJL/7BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAJL/7FCS/+zwkv/tiJL/7hiS/+6gVzPr/IM/6/yrR+v8y0/r/ONX6/zzW+v891vr/
PNb6/zjV+v8y0/r/KtH6/yDP+v8VzPr/JL/7qCS/+4Ykv/tiJL/7PCS/+xQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7GyS/+0Akv/tiJL/7giS/+58kv/u5GM36/x/P
+v8l0Pr/KNH6/ynR+v8o0fr/JdD6/x/P+v8Yzfr/JL/7uSS/+58kv/uCJL/7YiS/+0Akv/sbAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7GyS/+zwkv/ta
JL/7dSS/+40kv/uhJL/7siS/+74kv/vGFcz6/yS/+8Ykv/u+JL/7siS/+6Ekv/uNJL/7dSS/+1ok
v/s8JL/7GwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAJL/7FCS/+zAkv/tKJL/7YCS/+3Mkv/uCJL/7jSS/+5Qkv/uWJL/7lCS/+40kv/uCJL/7
cyS/+2Akv/tKJL/7MCS/+xQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7BSS/+x0kv/syJL/7RCS/+1Ikv/tcJL/7YiS/+2Qk
v/tiJL/7XCS/+1Ikv/tEJL/7MiS/+x0kv/sFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+wQkv/sUJL/7
ISS/+yokv/swJL/7MiS/+zAkv/sqJL/7ISS/+xQkv/sEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABAAEAICAAAAEAIACoEAAAAQAAAAAAPD94bWwgdmVyc2lvbj0iMS4w
IiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8YXNzZW1ibHkgeG1sbnM9InVy
bjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+CiAg
PGFzc2VtYmx5SWRlbnRpdHkKICAgIHZlcnNpb249IjEuMC4wLjAiCiAgICBwcm9jZXNzb3JBcmNo
aXRlY3R1cmU9IioiCiAgICBuYW1lPSJTdW5meWVyLkFJLkFzc2lzdGFudCIKICAgIHR5cGU9Indp
bjMyIgogIC8+CiAgPGRlc2NyaXB0aW9uPlN1bmZ5ZXIgQUkgQXNzaXN0YW50PC9kZXNjcmlwdGlv
bj4KICA8dHJ1c3RJbmZvIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MiI+
CiAgICA8c2VjdXJpdHk+CiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzPgogICAgICAgIDxyZXF1
ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4K
ICAgICAgPC9yZXF1ZXN0ZWRQcml2aWxlZ2VzPgogICAgPC9zZWN1cml0eT4KICA8L3RydXN0SW5m
bz4KICA8Y29tcGF0aWJpbGl0eSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTpjb21w
YXRpYmlsaXR5LnYxIj4KICAgIDxhcHBsaWNhdGlvbj4KICAgICAgPCEtLSBXaW5kb3dzIDEwICYg
MTEgLS0+CiAgICAgIDxzdXBwb3J0ZWRPUyBJZD0iezhlMGY3YTEyLWJmYjMtNGZlOC1iOWE1LTQ4
ZmQ1MGExNWE5YX0iLz4KICAgICAgPCEtLSBXaW5kb3dzIDguMSAtLT4KICAgICAgPHN1cHBvcnRl
ZE9TIElkPSJ7MWY2NzZjNzYtODBlMS00MjM5LTk1YmItODNkMGY2ZDBkYTc4fSIvPgogICAgICA8
IS0tIFdpbmRvd3MgOCAtLT4KICAgICAgPHN1cHBvcnRlZE9TIElkPSJ7NGEyZjI4ZTMtNTNiOS00
NDQxLWJhOWMtZDY5ZDRhNGE2ZTM4fSIvPgogICAgICA8IS0tIFdpbmRvd3MgNyAtLT4KICAgICAg
PHN1cHBvcnRlZE9TIElkPSJ7MzUxMzhiOWEtNWQ5Ni00ZmJkLThlMmQtYTI0NDAyMjVmOTNhfSIv
PgogICAgPC9hcHBsaWNhdGlvbj4KICA8L2NvbXBhdGliaWxpdHk+CiAgPGFwcGxpY2F0aW9uIHht
bG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+CiAgICA8d2luZG93c1NldHRp
bmdzPgogICAgICA8ZHBpQXdhcmUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20v
U01JLzIwMDUvV2luZG93c1NldHRpbmdzIj50cnVlL3BtPC9kcGlBd2FyZT4KICAgICAgPGRwaUF3
YXJlbmVzcyB4bWxucz0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9TTUkvMjAxNi9XaW5k
b3dzU2V0dGluZ3MiPlBlck1vbml0b3JWMiwgUGVyTW9uaXRvcjwvZHBpQXdhcmVuZXNzPgogICAg
PC93aW5kb3dzU2V0dGluZ3M+CiAgPC9hcHBsaWNhdGlvbj4KPC9hc3NlbWJseT4KAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAgAAAMAAAAqK4AAAAwAAAYAAAAEKBQoGCgcKCAoIigkKAAAABAAABQAAAA4KMA
pAikEKQYpBCnIKcwp0CnUKdgp3CngKeQp6CnsKfAp9Cn4KfwpwCoEKggqDCoQKhQqGCocKiAqJCo
oKiwqMCo0KjgqPCoAJAAABAAAAAIoCCgOKBAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA
===SUNFYER_EXE_END===

===SUNFYER_ICO_START===
AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sEJL/7FCS/+yEkv/sqJL/7MCS/+zIkv/swJL/7KiS/+yEk
v/sUJL/7BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sFJL/7HSS/+zIkv/tEJL/7UiS/+1wkv/tiJL/7
ZCS/+2Ikv/tcJL/7UiS/+0Qkv/syJL/7HSS/+wUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7FCS/+zAkv/tKJL/7YCS/+3Mk
v/uCJL/7jSS/+5Qkv/uWJL/7lCS/+40kv/uCJL/7cyS/+2Akv/tKJL/7MCS/+xQAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+xskv/s8JL/7
WiS/+3Ukv/uNJL/7oSS/+7Ikv/u+JL/7xhXM+v8kv/vGJL/7viS/+7Ikv/uhJL/7jSS/+3Ukv/ta
JL/7PCS/+xsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk
v/sbJL/7QCS/+2Ikv/uCJL/7nyS/+7kYzfr/H8/6/yXQ+v8o0fr/KdH6/yjR+v8l0Pr/H8/6/xjN
+v8kv/u5JL/7nyS/+4Ikv/tiJL/7QCS/+xsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAJL/7FCS/+zwkv/tiJL/7hiS/+6gVzPr/IM/6/yrR+v8y0/r/ONX6/zzW+v891vr/
PNb6/zjV+v8y0/r/KtH6/yDP+v8VzPr/JL/7qCS/+4Ykv/tiJL/7PCS/+xQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAACS/+wUkv/swJL/7WiS/+4Ikv/uoF836/yXQ+v8x0/r/PNb6/0XY
+v9L2vr/UNv6/1Hb+v9Q2/r/S9r6/0XY+v881vr/MdP6/yXQ+v8Xzfr/JL/7qCS/+4Ikv/taJL/7
MCS/+wUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7HSS/+0okv/t1JL/7nxXM+v8l0Pr/
M9T6/0HX+v9N2vr/V936/1/f+v9j4Pr/ZeD6/2Pg+v9f3/r/V936/03a+v9B1/r/M9T6/yXQ+v8V
zPr/JL/7nyS/+3Ukv/tKJL/7HQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/+wQkv/syJL/7YCS/
+40kv/u5IM/6/zHT+v9B1/r/UNv6/13e+v9o4fr/ceT6/3fl+v955vr/d+X6/3Hk+v9o4fr/Xd76
/1Db+v9B1/r/MdP6/yDP+v8kv/u5JL/7jSS/+2Akv/syJL/7BAAAAAAAAAAAAAAAAAAAAAAAAAAA
JL/7FCS/+0Qkv/tzJL/7oRjN+v8q0fr/PNb6/03a+v9d3vr/bOL6/3nm+v+E6Pr/i+r6/43r+v+L
6vr/hOj6/3nm+v9s4vr/Xd76/03a+v881vr/KtH6/xjN+v8kv/uhJL/7cyS/+0Qkv/sUAAAAAAAA
AAAAAAAAAAAAAAAAAAAkv/shJL/7UiS/+4Ikv/uyH8/6/zLT+v9F2Pr/V936/2jh+v955vr/iOn6
/5Xt+v+e7/r/ofD6/57v+v+V7fr/iOn6/3nm+v9o4fr/V936/0XY+v8y0/r/H8/6/yS/+7Ikv/uC
JL/7UiS/+yEAAAAAAAAAAAAAAAAAAAAAAAAAACS/+yokv/tcJL/7jSS/+74l0Pr/ONX6/0va+v9f
3/r/ceT6/4To+v+V7fr/pPH6/7D0+v+19fr/sPT6/6Tx+v+V7fr/hOj6/3Hk+v9f3/r/S9r6/zjV
+v8l0Pr/JL/7viS/+40kv/tcJL/7KgAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7MCS/+2Ikv/uUJL/7
xijR+v881vr/UNv6/2Pg+v935fr/i+r6/57v+v+w9Pr/wfj6/8n6+v/B+Pr/sPT6/57v+v+L6vr/
d+X6/2Pg+v9Q2/r/PNb6/yjR+v8kv/vGJL/7lCS/+2Ikv/swAAAAAAAAAAAAAAAAAAAAACS/+wAk
v/syJL/7ZCS/+5YVzPr/KdH6/z3W+v9R2/r/ZeD6/3nm+v+N6/r/ofD6/7X1+v/J+vr/3f/6/8n6
+v+19fr/ofD6/43r+v955vr/ZeD6/1Hb+v891vr/KdH6/xXM+v8kv/uWJL/7ZCS/+zIkv/sAAAAA
AAAAAAAAAAAAAAAAACS/+zAkv/tiJL/7lCS/+8Yo0fr/PNb6/1Db+v9j4Pr/d+X6/4vq+v+e7/r/
sPT6/8H4+v/J+vr/wfj6/7D0+v+e7/r/i+r6/3fl+v9j4Pr/UNv6/zzW+v8o0fr/JL/7xiS/+5Qk
v/tiJL/7MAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7KiS/+1wkv/uNJL/7viXQ+v841fr/S9r6/1/f
+v9x5Pr/hOj6/5Xt+v+k8fr/sPT6/7X1+v+w9Pr/pPH6/5Xt+v+E6Pr/ceT6/1/f+v9L2vr/ONX6
/yXQ+v8kv/u+JL/7jSS/+1wkv/sqAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/shJL/7UiS/+4Ikv/uy
H8/6/zLT+v9F2Pr/V936/2jh+v955vr/iOn6/5Xt+v+e7/r/ofD6/57v+v+V7fr/iOn6/3nm+v9o
4fr/V936/0XY+v8y0/r/H8/6/yS/+7Ikv/uCJL/7UiS/+yEAAAAAAAAAAAAAAAAAAAAAAAAAACS/
+xQkv/tEJL/7cyS/+6EYzfr/KtH6/zzW+v9N2vr/Xd76/2zi+v955vr/hOj6/4vq+v+N6/r/i+r6
/4To+v955vr/bOL6/13e+v9N2vr/PNb6/yrR+v8Yzfr/JL/7oSS/+3Mkv/tEJL/7FAAAAAAAAAAA
AAAAAAAAAAAAAAAAJL/7BCS/+zIkv/tgJL/7jSS/+7kgz/r/MdP6/0HX+v9Q2/r/Xd76/2jh+v9x
5Pr/d+X6/3nm+v935fr/ceT6/2jh+v9d3vr/UNv6/0HX+v8x0/r/IM/6/yS/+7kkv/uNJL/7YCS/
+zIkv/sEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7HSS/+0okv/t1JL/7nxXM+v8l0Pr/M9T6
/0HX+v9N2vr/V936/1/f+v9j4Pr/ZeD6/2Pg+v9f3/r/V936/03a+v9B1/r/M9T6/yXQ+v8VzPr/
JL/7nyS/+3Ukv/tKJL/7HQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sFJL/7MCS/+1ok
v/uCJL/7qBfN+v8l0Pr/MdP6/zzW+v9F2Pr/S9r6/1Db+v9R2/r/UNv6/0va+v9F2Pr/PNb6/zHT
+v8l0Pr/F836/yS/+6gkv/uCJL/7WiS/+zAkv/sFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAkv/sUJL/7PCS/+2Ikv/uGJL/7qBXM+v8gz/r/KtH6/zLT+v841fr/PNb6/z3W+v881vr/
ONX6/zLT+v8q0fr/IM/6/xXM+v8kv/uoJL/7hiS/+2Ikv/s8JL/7FAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sbJL/7QCS/+2Ikv/uCJL/7nyS/+7kYzfr/H8/6/yXQ
+v8o0fr/KdH6/yjR+v8l0Pr/H8/6/xjN+v8kv/u5JL/7nyS/+4Ikv/tiJL/7QCS/+xsAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sbJL/7PCS/+1okv/t1
JL/7jSS/+6Ekv/uyJL/7viS/+8YVzPr/JL/7xiS/+74kv/uyJL/7oSS/+40kv/t1JL/7WiS/+zwk
v/sbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAkv/sUJL/7MCS/+0okv/tgJL/7cyS/+4Ikv/uNJL/7lCS/+5Ykv/uUJL/7jSS/+4Ikv/tzJL/7
YCS/+0okv/swJL/7FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAkv/sFJL/7HSS/+zIkv/tEJL/7UiS/+1wkv/tiJL/7ZCS/+2Ik
v/tcJL/7UiS/+0Qkv/syJL/7HSS/+wUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJL/7BCS/+xQkv/shJL/7
KiS/+zAkv/syJL/7MCS/+yokv/shJL/7FCS/+wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAACS/+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA=
===SUNFYER_ICO_END===
